export const ReasonSupport = [
    {
        id: 1,
        reason: "Porta convallis. Integer magna orci, consequat ac nisl vel, tristique dictum sapien. Nam iaculis sit amet sem a porttitor. Cras vestibulum tempor ligula eu vehicula. Nam sed purus augue. Donec non semper arcu.",
        datePosted: new Date(2019, 6, 30),
        organizer: "Mr. Dude",
        description: "NUS Student",
        anonymous: false,
    },
    {
        id: 2,
        reason: "Porta convallis. Integer magna orci, consequat ac nisl vel, tristique dictum sapien. Nam iaculis sit amet sem a porttitor. Cras vestibulum tempor ligula eu vehicula. Nam sed purus augue. Donec non semper arcu.",
        datePosted: new Date(2019, 7, 10),
        organizer: "Jack",
        description: "President of Club",
        anonymous: true,
    },
    {
        id: 3,
        reason: "Porta convallis. Integer magna orci, consequat ac nisl vel, tristique dictum sapien. Nam iaculis sit amet sem a porttitor. Cras vestibulum tempor ligula eu vehicula. Nam sed purus augue. Donec non semper arcu.",
        datePosted: new Date(2019, 7, 12),
        organizer: "DX",
        description: "Emperor",
        anonymous: false,
    },
    {
        id: 4,
        reason: "Porta convallis. Integer magna orci, consequat ac nisl vel, tristique dictum sapien. Nam iaculis sit amet sem a porttitor. Cras vestibulum tempor ligula eu vehicula. Nam sed purus augue. Donec non semper arcu.",
        datePosted: new Date(2019, 7, 20),
        organizer: "Phaedra",
        description: "Gurl",
        anonymous: false,
    },
    {
        id: 5,
        reason: "Porta convallis. Integer magna orci, consequat ac nisl vel, tristi.",
        datePosted: new Date(2019, 7, 22),
        organizer: "Jane",
        description: "President",
        anonymous: true,
    },
    {
        id: 6,
        reason: "Porta convallis. Integer magna orci, consequat ac nisl vel, tristique dictum sapien. Nam iaculis sit amet sem a porttitor. que dictum sapien. Nam iaculis sit amet sem a porttitor. Cras vestibulum tempor ligula eu vehicula. Nam sed purus augue. Donec non semper arcu Cras vestibulum tempor ligula eu vehicula. Nam sed purus augue. Donec non semper arcu.",
        datePosted: new Date(2019, 7, 27),
        organizer: "Meowth",
        description: "That's right",
        anonymous: true,
    },
]